algoritmo "aula 2A - trabalhando com tipos"

var
   palavra1, palavra2, palavra3: literal
   numero1, numero2, numero3: inteiro

inicio
   escreva("Palavra 1: ")
   leia(palavra1)

   escreva("Palavra 2: ")
   leia(palavra2)

   escreva("Número 1: ")
   leia(numero1)

   escreva("Número 2: ")
   leia(numero2)
   
   palavra3 <- palavra1 + palavra2
   numero3 <- numero1 + numero2
   
   escreval(palavra3)
   escreval(numero3)
fimalgoritmo
